### ISSUE TITLE
A comment

### ISSUE THREAD

**Issue by ieee-wangwei** [Xu-yuan/NumGuess#1]
Your code is very good, the method of making the random number is quite easy. I want to give you a small suggestion, you can fix the code, and make it display the result only when you input"N".

**Comment by Xu-yuan** [comment]
thanks for your commit, i will change it later.

**Comment by cpxdudu** [comment]
The code is perfect and the form is easy to read as well . The only thing is that the result of how many times have you play should appear at the last of the game .
